# %% [markdown]
# ## 7. Conclusiones generales
# - **Desempeño del modelo:** la **regresión logística con umbral ajustado (0,615)** es el modelo final. En el conjunto de prueba obtiene F1 = 0,473 (IC95 % 0,453–0,494), Recall 0,58, Precision 0,40 y ROC-AUC 0,80, y en 1.000 registros nunca vistos, F1 = 0,495. Ni los modelos flexibles (Random Forest, SVM) ni los ensambles (votación, bagging, XGBoost) la superaron: las pruebas estadísticas mostraron equivalencia en F1, y se eligió el modelo más simple e interpretable. La mayor mejora vino de **ajustar el umbral de decisión**, no de cambiar de algoritmo.
# - **Aporte de la regla prescriptiva:** las bandas de acompañamiento convierten la probabilidad en decisiones. En el pool de 42.357 estudiantes, la tasa real de alto desempeño va del 3,7 % en prioridad de nivelación al 40,9 % en alto potencial. Los colegios oficiales rurales (72,6 % en prioridad), las jornadas nocturna y sabatina (más del 93 %) y municipios del Bajo Cauca, Urabá y el Nordeste concentran la mayor necesidad.
# - **Calidad y preparación de los datos:** el conjunto 2022-2 de Antioquia venía con el 50 % de filas duplicadas. Las reglas de calidad y las aserciones lo detectaron, y la limpieza dejó 72.357 estudiantes con 17,1 % de alto desempeño. Los faltantes resultaron informativos (quien no reporta datos suele tener menor desempeño), por lo que se imputaron con una categoría explícita e indicadores en lugar de eliminarse.
# - **Análisis por grupos (equidad):** el modelo funciona peor donde más se necesita. El F1 es de 0,34 en colegios oficiales frente a 0,65 en no oficiales, y de 0,38 fuera del Valle de Aburrá frente a 0,50 dentro. Además, sobrepredice el alto desempeño en hombres. Reproduce las desigualdades del sistema educativo que ya mostraba el análisis exploratorio (2.5).
# - **Valor estratégico:** revisando solo al 20 % de los estudiantes con mayor probabilidad se capta a la mitad de los de alto desempeño (lift 2,5). Esto permite focalizar programas de becas, preparación o nivelación con recursos limitados, siempre como apoyo a la decisión y nunca para excluir a nadie.
# - **Criterio de negocio:** se cumplen los tres criterios definidos en 1.5: Recall 0,58 ≥ 0,55, lift 2,33 ≥ 2 y F1 0,473 > 0,459. Los márgenes son modestos, y la curva de aprendizaje muestra que con estas variables el techo de F1 ronda 0,47–0,49. Mejorar exige **más información**, no más datos ni modelos más complejos.

# %% [markdown]
# ### Recomendaciones
# - **Reentrenar periódicamente** con cada nueva cohorte de la prueba Saber 11 (datos abiertos del ICFES) y comparar el desempeño entre cohortes para detectar *drift*.
# - **Construir un tablero de bandas por municipio y colegio** para las secretarías de educación, contrastando siempre la banda predicha con los resultados reales del municipio, como muestra el caso de Andes.
# - **Incorporar el efecto colegio** (el promedio histórico del establecimiento en cohortes anteriores) y variables exógenas del territorio (conectividad, índices de pobreza multidimensional, oferta educativa) para superar el techo actual de desempeño.
# - **Calibrar las probabilidades** (por ejemplo, con `CalibratedClassifierCV`) si se van a comunicar como riesgos o probabilidades de éxito, ya que el submuestreo las infla.
# - **Usar las bandas para focalizar, no para excluir:** asignar tipos de acompañamiento según la banda, revisar las decisiones con criterio pedagógico y auditar periódicamente la equidad por naturaleza, zona, subregión y género.
